### ISSUE TITLE
7060mff测试黑屏

### ISSUE THREAD

**Issue by wczhashi** [W-MS/OptiPlex-7060and7070-Catalina#9]
7060mff   Catalina测试在第一阶段白苹果logo走进度到一半时黑屏无法继续安装，显卡注入12345678可进行安装，装完后取消注入则继续黑屏
型号：7060MFF
CPU：15-8500t
显卡：uhd630
内存：ddr4 8g
硬盘：128 固态+500机械

**Comment by W-MS** [comment]
DVMT修改了吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wczhashi <notifications@github.com&gt;
发送时间: 2019年12月23日 11:00
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 7060mff测试黑屏 (#9)




7060mff   Catalina测试在第一阶段白苹果logo走进度到一半时黑屏无法继续安装，显卡注入12345678可进行安装，装完后取消注入则继续黑屏

**Comment by wczhashi** [comment]
**修改了，但是是否成功不知道，请看执行后的代码：**

![微信图片_20191225135640](https://user-images.githubusercontent.com/17957587/71434214-6f6ae500-271e-11ea-8bef-43cdbe4d8d18.jpg)

执行更改代码后提示如此，

STAT Operation也已改为AHCI

详述一下：

1.如果不注入0x12345678，进度条都到大概一半的时候会直接黑屏，无法查看是卡代码还是什么原因，如图，大致走到这个位置：

![微信图片_20191225140150](https://user-images.githubusercontent.com/17957587/71434372-26676080-271f-11ea-8503-7fe7154b7605.jpg)

2.如果注入0x12345678，则可成功安装系统进硬盘，但此时显卡有问题。VRAM只有14M，并且鼠标运动比较卡，使用过程中有自动关机的现象，不知是否和显卡有关，如图：

![微信图片_20191225141205](https://user-images.githubusercontent.com/17957587/71434687-8d394980-2720-11ea-9ea2-d2525fec9483.jpg)

**Comment by W-MS** [comment]
确实是DVMT的问题，考虑到运行setup_var输出似乎不太正常，建议你通过dell pfs extract工具提取一下bios，使用Universal IFR extractor解码，看看DVMT的offset是否一致。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wczhashi <notifications@github.com&gt;
发送时间: 2019年12月25日 14:33
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: W-MS <w.ms@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 7060mff测试黑屏 (#9)



 
DVMT修改了吗发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: wczhashi <notifications@github.com&gt; 发送时间: 2019年12月23日 11:00 收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 7060mff测试黑屏 (#9) 7060mff Catalina测试在第一阶段白苹果logo走进度到一半时黑屏无法继续安装，显卡注入12345678可进行安装，装完后取消注入则继续黑屏 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
 修改了，但是是否成功不知道，请看执行后的代码：
  

 
执行更改代码后提示如此，
 STAT Operation也已改为AHCI
 详述一下：
 1.如果不注入0x12345678，进度条都到大概一半的时候会直接黑屏，无法查看是卡代码还是什么原因，如图，大致走到这个位置：
 

 
2.如果注入0x12345678，则可成功安装系统进硬盘，但此时显卡有问题。VRAM只有14M，并且鼠标运动比较卡，使用过程中有自动关机的现象，不知是否和显卡有关，如图：

**Comment by wczhashi** [comment]
ok

**Comment by paranoea** [comment]
我这边的 7070 试下一下 0x8dc 没有效果，确实进度条到一半就重启了，请问一下在mac上可以dump bios吗？没找到相应的工具，谢谢

**Comment by paranoea** [comment]
搞定了，0x8dc没问题的，好像又把CFG Lock关掉才好 0x5be 改成0x0，两个都改了，可以启动了

**Comment by wczhashi** [comment]
之前一直忽略了一个问题，由于我的显示器并没有dp接口，所以使用了绿联的dp转hdmi，黑屏问题就是此转接头引起。
经测试，显卡id改回正常值之后，开机后虽然显示器失去信号，但是远程链接可以进入系统，查看显存是1500MB左右，所以，在不更改现有硬件的基础上，如果能找到解决被动式dp转接器正常工作的方法，7060这个机器就没什么问题了

**Comment by BosonLiu** [comment]
> 搞定了，0x8dc没问题的，好像又把CFG Lock关掉才好 0x5be 改成0x0，两个都改了，可以启动了

老哥，我根据你的提示修改了，但依然还是会重启，请问是不是还需要修改什么
